"""notes_app — a small FastAPI notes service that uses the runtime.

This is a plain web app: no agents, no LLM calls. The point is to
demonstrate that the runtime serves a normal Python web app just as well
as an agent-containing one.

Run with:

    pip install pyxen[examples]      # adds fastapi + uvicorn
    pyxen validate runtime.json
    uvicorn examples.notes_app.app:app --reload

Endpoints:

    POST /notes        — create a note (auth via runtime.identity)
    GET  /notes        — list all notes
    GET  /notes/{id}   — fetch a single note
    DELETE /notes/{id} — remove a note
    GET  /healthz      — liveness probe (no runtime)
"""

from __future__ import annotations

import os
import uuid
from contextlib import asynccontextmanager
from datetime import UTC, datetime
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse

from pyxen import Runtime

RUNTIME_PATH = os.environ.get("PYXEN_RUNTIME", "runtime.json")


@asynccontextmanager
async def lifespan(app: FastAPI) -> Any:
    """Load the runtime on startup; close nothing (runtime is stateless)."""
    rt = await Runtime.load(RUNTIME_PATH)
    app.state.runtime = rt
    yield


app = FastAPI(
    title="pyxen notes",
    version="0.1.0",
    description="A small notes service. The interesting bit is that every environment-shaped concern goes through the runtime.",
    lifespan=lifespan,
)


def _now_iso() -> str:
    return datetime.now(UTC).isoformat()


def _rt() -> Runtime:
    rt: Runtime | None = getattr(app.state, "runtime", None)
    if rt is None:
        raise HTTPException(status_code=503, detail="runtime not loaded")
    return rt


@app.get("/")
async def index() -> HTMLResponse:
    """Tiny HTML landing so the root URL isn't a FastAPI 404.

    FastAPI returns ``{"detail": "Not Found"}`` for unmapped paths; on a
    freshly-loaded app the root would do that. This page is what a browser
    sees when it opens the service from the cutuy-www landing card.
    """
    return HTMLResponse(
        """<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Notes (pyxen)</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: #0f0f0f; color: #e0e0e0;
            min-height: 100vh; margin: 0; padding: 40px 20px;
            display: flex; flex-direction: column; align-items: center;
        }}
        h1 {{ font-size: 2.2em; color: #fff; margin-bottom: 4px; }}
        .subtitle {{ color: #888; margin-bottom: 32px; }}
        .endpoints {{ max-width: 640px; width: 100%; }}
        .endpoint {{
            background: #1a1a1a; border: 1px solid #333; border-radius: 10px;
            padding: 14px 18px; margin-bottom: 10px;
            display: flex; gap: 16px; align-items: baseline;
        }}
        .method {{
            font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
            font-size: 0.78em; font-weight: 600; padding: 3px 8px;
            border-radius: 4px; min-width: 56px; text-align: center;
        }}
        .get {{ background: #1e3a5f; color: #93c5fd; }}
        .post {{ background: #1f4a35; color: #86efac; }}
        .delete {{ background: #4a1f1f; color: #fca5a5; }}
        code {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; color: #1abc9c; }}
        a {{ color: #1abc9c; }}
        footer {{ margin-top: 40px; color: #555; font-size: 0.8em; }}
    </style>
</head>
<body>
    <h1>📝 Notes (pyxen)</h1>
    <p class="subtitle">A FastAPI notes service backed by the pyxen userland runtime.</p>
    <div class="endpoints">
        <div class="endpoint"><span class="method get">GET</span><code>/</code> this page</div>
        <div class="endpoint"><span class="method get">GET</span><code>/healthz</code> liveness probe</div>
        <div class="endpoint"><span class="method get">GET</span><code>/notes</code> list all notes</div>
        <div class="endpoint"><span class="method post">POST</span><code>/notes</code> create a note (body: <code>{{"text": "..."}}</code>)</div>
        <div class="endpoint"><span class="method get">GET</span><code>/notes/&lt;id&gt;</code> fetch one note</div>
        <div class="endpoint"><span class="method delete">DELETE</span><code>/notes/&lt;id&gt;</code> remove a note</div>
        <div class="endpoint"><span class="method get">GET</span><code>/docs</code> Swagger UI (auto-generated by FastAPI)</div>
    </div>
    <footer>source: <code>pyxen/examples/notes_app/</code> · port 18810 · pyxen v0.2.0a1</footer>
</body>
</html>"""
    )


@app.get("/healthz")
async def healthz() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/notes")
async def create_note(body: dict[str, Any]) -> dict[str, Any]:
    rt = _rt()
    text = body.get("text")
    if not isinstance(text, str) or not text.strip():
        raise HTTPException(status_code=400, detail="text is required")

    async with rt.observability.trace("create_note") as span:
        me = await rt.identity.current()
        span.set_attribute("author", me.id)

        # Reject anonymous in any non-dev environment
        if me.id == "anonymous" and os.environ.get("PYXEN_ALLOW_ANON") != "1":
            raise HTTPException(status_code=401, detail="authentication required")

        # Soft budget check before writing
        check = await rt.tokens.check("notes-write", 100)
        if not check.allowed:
            raise HTTPException(status_code=429, detail=check.reason or "rate limited")

        note_id = str(uuid.uuid4())
        note = {
            "id": note_id,
            "text": text,
            "author": me.id,
            "created_at": _now_iso(),
        }
        await rt.storage.put("notes", note_id, note)
        await rt.tokens.charge("notes-write", tokens=100, dollars=0.0)
        return note


@app.get("/notes")
async def list_notes() -> list[dict[str, Any]]:
    rt = _rt()
    notes: list[dict[str, Any]] = await rt.storage.query("notes")
    return notes


@app.get("/notes/{note_id}")
async def get_note(note_id: str) -> dict[str, Any]:
    rt = _rt()
    note = await rt.storage.get("notes", note_id)
    if note is None:
        raise HTTPException(status_code=404, detail="note not found")
    return note or {}


@app.delete("/notes/{note_id}", status_code=204)
async def delete_note(note_id: str) -> None:
    rt = _rt()
    deleted = await rt.storage.delete("notes", note_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="note not found")


def _main() -> None:
    """Smoke test: import the app, exercise the endpoints in-process."""
    import asyncio
    import os
    import tempfile
    from pathlib import Path

    # Use a temp runtime.json so the test is hermetic
    with tempfile.TemporaryDirectory() as tmp:
        os.chdir(tmp)
        manifest = {
            "version": "1",
            "identity": {"implementation": "env", "config": {}},
            "tokens": {"implementation": "json_budget", "config": {"path": str(Path(tmp) / "b.json")}},
            "ipc": {"implementation": "inproc", "config": {}},
            "pkg": {"implementation": "dry_run", "config": {}},
            "storage": {"implementation": "inmemory", "config": {}},
            "secrets": {"implementation": "dotenv", "config": {"path": str(Path(tmp) / ".env")}},
            "observability": {"implementation": "null", "config": {}},
        }
        Path("runtime.json").write_text(str(manifest).replace("'", '"'))

        os.environ["PYXEN_IDENTITY_ID"] = "test-user"
        os.environ["PYXEN_ALLOW_ANON"] = "1"

        async def go() -> None:
            # Use FastAPI's TestClient via httpx for in-process requests
            try:
                import httpx  # noqa: F401
            except ImportError:
                # No httpx — fall back to a basic smoke test
                rt = await Runtime.load("runtime.json")
                me = await rt.identity.current()
                assert me.id == "test-user"
                await rt.storage.put("notes", "test", {"id": "test", "text": "hi"})
                note = await rt.storage.get("notes", "test")
                assert note is not None
                assert note["text"] == "hi"
                return

            from fastapi.testclient import TestClient

            with TestClient(app) as client:
                # The lifespan loads the runtime; create a note
                r = client.post("/notes", json={"text": "hello runtime"})
                assert r.status_code == 200, r.text
                note = r.json()
                assert "id" in note
                assert note["text"] == "hello runtime"
                assert note["author"] == "test-user"

                # List notes
                r = client.get("/notes")
                assert r.status_code == 200
                assert len(r.json()) == 1

                # Get a single note
                r = client.get(f"/notes/{note['id']}")
                assert r.status_code == 200
                assert r.json()["text"] == "hello runtime"

                # Delete it
                r = client.delete(f"/notes/{note['id']}")
                assert r.status_code == 204

                # Now it's gone
                r = client.get(f"/notes/{note['id']}")
                assert r.status_code == 404

        asyncio.run(go())


if __name__ == "__main__":
    _main()
